// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pondziaqsdxoxefzbssy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbmR6aWFxc2R4b3hlZnpic3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNzU5MDMsImV4cCI6MjA1NDc1MTkwM30.S36dD85rIaXOoYZx12twXKOKbe7AH300gi0WQb0qCO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);